FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src
COPY assets/ ./assets

CMD ["python", "src/app.py"]  # Change 'app.py' to the name of your main script if different
